<a href="https://colab.research.google.com/github/mckore/Explore_Projects_Tutorials/blob/master/CS_310_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import math as ma

HW Questions: Section 1.1 - 1,2,4,8,15,20 
Class Problems: a) 12.3 b) -11.001001001 c) .15050505  d) 3.0939393939

Question 1:

In [47]:
data = {
    "m1":[1,2,2,17,-6,0,-10,-10**30,10**29],
    "n1":[20,21,20,72,4,40,-1,10**30,10**30]
}
df = pd.DataFrame(data)

In [10]:
m=df.m1
n=df.n1

In [11]:
#if definition of "between" m<= i <=n
x=n-m+1
print(x)

0                                 20
1                                 20
2                                 19
3                                 56
4                                 11
5                                 41
6                                 10
7    2000000000000000000000000000001
8     900000000000000000000000000001
dtype: object


In [12]:
#if by "between" means m < i < n 
y = n-m-1
print(y)

0                                 18
1                                 18
2                                 17
3                                 54
4                                  9
5                                 39
6                                  8
7    1999999999999999999999999999999
8     899999999999999999999999999999
dtype: object


Question 2:

In [40]:
#a How many 4 digit numbers are there
9999-1000+1

9000

In [42]:
#Question 2: b:d
#Ending in 1 would be a multiple of 10...
#answers are the same for ending in 0 , and multiples of 10 
ma.floor(99999/10)-ma.floor((10000-1)/10)
#or
9*10*10*10*1

9000

Question 4:

In [36]:
#Question 4: a:e
fl = np.array([ma.ceil(0.763), #a
               (2*ma.ceil(0.6))-ma.ceil(1.2), #b
               ma.ceil(1.1)+ma.ceil(3.3), #c
               ma.ceil(ma.sqrt(3))-ma.floor(ma.sqrt(3)), #d
               ma.ceil(-73)-ma.floor(-73)]) #e
fl

array([1, 0, 6, 1, 0])

Question 8:

In [2]:
n8 = np.array([80,100,2967,34, 10**5, 3400])
m8=np.array([1,0,9,-6,10**4,-600])

In [3]:
np.array([3, 7]) - np.array([1, 2])

array([2, 5])

In [4]:
a = np.floor(n8/10)-np.floor((m8-1)/10)

In [6]:
np.set_printoptions(suppress=True)

In [7]:
print(a)

[   8.   11.  296.    4. 9001.  401.]


Question 15:

Question 20: 